"""The index's one-line blurbs carry no links, and repair passes leave generated files alone.

A repair_links run on the real wiki reported this:

    index.md: fixed 5918 (0 nested, 5900 bad-path, 0 reader-url, 18 dangling)
    log.md:   fixed 136  (0 nested, 0 bad-path, 0 reader-url, 136 dangling)

Both numbers are real, and neither should have been repaired.

wiki/index.md is regenerated by _rebuild_index at the end of every ingest, so a repair is
erased within the hour — and the links were broken by the generator in the first place.
first_desc_line lifts a page's opening prose line verbatim, and the autolinker wrote every
link in it relative to THAT page's directory: `../entities/cnn.md` is correct inside
wiki/entities/kaitlan-collins.md and resolves outside the wiki entirely once it is sitting
in wiki/index.md. Truncating to 120 characters made it worse, because that cut routinely
lands inside a URL and leaves `[White House](../ent` on the page as literal text.

wiki/log.md is the append-only audit trail. Unwrapping 136 dead links in it rewrites the
record of what happened.

And the deciding argument for both: _snapshot_version skips index.md and log.md by name,
so a write to either is the one edit in tools/ that CANNOT be reverted. Every other write
path already refuses them — _update_file by name, the section tools via their `_reserved`
tuple — and repair_links was the only one that did not.
"""
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from harness import TempWikiTestCase

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tools"))
import agent
import repair_links


class IndexDescriptionTest(TempWikiTestCase):

    def _wiki(self):
        self.w.page("entities/kaitlan-collins.md", title="Kaitlan Collins", type="entity",
                    body="# Kaitlan Collins\n\nA [CNN](../entities/cnn.md) journalist who "
                         "covers the [White House](../entities/white-house.md).\n")
        self.w.page("entities/cnn.md", title="CNN", type="entity",
                    body="# CNN\n\nA news network.\n")
        agent._rebuild_index({})

    def test_the_blurb_has_no_links_in_it(self):
        self._wiki()
        idx = (agent.WIKI_DIR / "index.md").read_text(encoding="utf-8")
        line = next(l for l in idx.splitlines() if "Kaitlan" in l)
        # One link: the entry's own link to the page. None from the borrowed prose.
        self.assertEqual(line.count("]("), 1, line)
        self.assertIn("A CNN journalist who covers the White House.", line)

    def test_the_entrys_own_link_still_works(self):
        self._wiki()
        idx = (agent.WIKI_DIR / "index.md").read_text(encoding="utf-8")
        self.assertIn("[Kaitlan Collins](entities/kaitlan-collins.md)", idx)
        self.assertTrue((agent.WIKI_DIR / "entities" / "kaitlan-collins.md").is_file())

    def test_a_long_line_is_never_cut_inside_a_link(self):
        # Truncating first left `[White House](../ent` rendering as literal text.
        self.w.page("entities/long.md", title="Long Corp", type="entity",
                    body="# Long Corp\n\nA firm that does many things in many places over "
                         "a long period of years and also works with the "
                         "[White House](../entities/white-house.md) on procurement.\n")
        agent._rebuild_index({})
        idx = (agent.WIKI_DIR / "index.md").read_text(encoding="utf-8")
        line = next(l for l in idx.splitlines() if "Long Corp" in l)
        self.assertEqual(line.count("]("), 1, line)
        self.assertNotIn("](../", line, "a severed link survived into the index")

    def test_the_index_it_generates_has_no_broken_links(self):
        # The real assertion: generate, then ask the repair pass whether anything is wrong.
        self._wiki()
        idx = agent.WIKI_DIR / "index.md"
        for m in repair_links._LINK_RE.finditer(idx.read_text(encoding="utf-8")):
            target = (idx.parent / m.group(2)).resolve()
            self.assertTrue(target.is_file(), f"index links to nothing: {m.group(0)}")


class GeneratedFilesAreLeftAloneTest(TempWikiTestCase):

    def _with_dead_links(self):
        self.w.page("entities/a.md", title="A Corp", type="entity",
                    body="# A Corp\n\n## Overview\n\nA firm.\n")
        for name, text in (
            ("index.md", "# Wiki Index\n\n- [Gone](entities/gone.md)\n"),
            ("log.md", "# Log\n\n- 2026-09-22 wrote [Gone](entities/gone.md)\n"),
        ):
            (agent.WIKI_DIR / name).write_text(text, encoding="utf-8")
        (agent.WIKI_DIR / "entities" / "index.md").write_text(
            "# Entities\n\n- [Gone](gone.md)\n", encoding="utf-8")

    def test_the_root_index_is_not_rewritten(self):
        self._with_dead_links()
        before = (agent.WIKI_DIR / "index.md").read_text(encoding="utf-8")
        repair_links.repair_links()
        self.assertEqual((agent.WIKI_DIR / "index.md").read_text(encoding="utf-8"), before,
                         "a generated file was repaired; _rebuild_index will undo it")

    def test_a_subdirectory_index_is_not_rewritten_either(self):
        self._with_dead_links()
        p = agent.WIKI_DIR / "entities" / "index.md"
        before = p.read_text(encoding="utf-8")
        repair_links.repair_links()
        self.assertEqual(p.read_text(encoding="utf-8"), before)

    def test_the_log_is_not_rewritten(self):
        # Append-only, and unrevertable: _snapshot_version skips it by name.
        self._with_dead_links()
        before = (agent.WIKI_DIR / "log.md").read_text(encoding="utf-8")
        repair_links.repair_links()
        self.assertEqual((agent.WIKI_DIR / "log.md").read_text(encoding="utf-8"), before,
                         "the audit trail was edited, and it cannot be reverted")

    def test_the_skipped_files_are_exactly_the_ones_nothing_can_revert(self):
        # The rule, not the list: if _snapshot_version will not record it, no repair pass
        # may write it. Keeps the two from drifting apart.
        for name in repair_links._GENERATED:
            p = agent.WIKI_DIR / name
            p.write_text("# X\n\ncontent\n", encoding="utf-8")
            agent._atomic_write(p, "# X\n\nchanged\n")
            hist = agent.HISTORY_DIR / name
            self.assertFalse(hist.exists() and any(hist.glob("*.md")),
                             f"{name} is revertable now — it may not need skipping")

    def test_an_ordinary_page_is_still_repaired(self):
        self._with_dead_links()
        self.w.page("concepts/x.md", title="X", type="concept",
                    body="# X\n\n## Definition\n\nSee [Gone](../entities/gone.md).\n")
        repair_links.repair_links()
        self.assertIn("See Gone.", self.w.disk("concepts/x.md"))

    def test_a_hand_maintained_list_is_still_repaired(self):
        # reading-list.md and tasks.md get history and are nobody's generated output, so a
        # dead link in them is a dead link worth fixing.
        self.w.page("entities/a.md", title="A Corp", type="entity",
                    body="# A Corp\n\n## Overview\n\nA firm.\n")
        p = agent.WIKI_DIR / "reading-list.md"
        p.write_text("# Reading List\n\n- [Gone](entities/gone.md)\n", encoding="utf-8")
        repair_links.repair_links()
        self.assertIn("- Gone\n", p.read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
