#!/usr/bin/env python3
"""
Show — and undo — everything a named maintenance pass wrote.

Every write records its reason in the revision filename (`<ts>__repair-links.md`), which
makes a whole pass addressable after the fact. Reverting one page at a time from its
History view is fine for one bad repair; it is not an answer to "that pass touched 900
pages and I want them back".

    python3 tools/undo_pass.py repair-links --dry-run   # what it changed, and what reverting would restore
    python3 tools/undo_pass.py repair-links             # put it all back
    python3 tools/undo_pass.py repair-links --diff      # full unified diff per page

A page is only reverted when the pass's write was the LAST thing to touch it. A revision
file holds the content as it was BEFORE the write that produced it, so the newest revision
being stamped `__repair-links` is exactly what "the repair is still the current content"
means. If anything wrote afterwards — an ingest, a hand edit — reverting would throw that
away, so the page is reported under "skipped" and left alone. Undoing a repair must not
cost you the work that came after it.

Pages the pass wrote but which keep no history (`index.md`, `log.md` — see
agent._snapshot_version) cannot be restored from here and are reported as such.

The revert itself goes through agent._atomic_write, so it is recorded like any other write
and can be undone in turn.
"""
import difflib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import agent
from agent import _atomic_write, write_reason, begin_write_scope

_NO_HISTORY = ("index.md", "log.md")


def _revisions(page_dir: Path):
    """(path, reason) for each stored revision, oldest first. Lexical order is
    chronological by construction — the timestamp prefix is fixed width."""
    out = []
    for f in sorted(page_dir.glob("*.md")):
        stem = f.stem
        out.append((f, stem.split("__", 1)[1] if "__" in stem else ""))
    return out


def plan(reason: str):
    """Returns (revertable, skipped) — each a list of (page, revision, why)."""
    history, wiki = agent.HISTORY_DIR, agent.WIKI_DIR
    revertable, skipped = [], []
    if not history.is_dir():
        return revertable, skipped
    for page_dir in sorted(history.rglob("*.md")):
        if not page_dir.is_dir():
            continue                      # a stray file, not a page's revision directory
        revs = _revisions(page_dir)
        if not revs:
            continue
        mine = [r for r in revs if r[1] == reason]
        if not mine:
            continue
        page = wiki / page_dir.relative_to(history)
        if not page.exists():
            skipped.append((page, None, "the page no longer exists"))
            continue
        # The newest revision names the write that produced the CURRENT content.
        if revs[-1][1] != reason:
            skipped.append((page, None,
                            f"written again since, by {revs[-1][1] or 'an unlabelled pass'}"
                            f" — reverting would discard that"))
            continue
        # Restore the oldest state this pass wrote over, so a pass that touched one page
        # several times is undone as a whole rather than one write at a time.
        skipped_inner = False
        for i, (_f, why) in enumerate(revs):
            if why == reason:
                # Everything from here on must also be this pass, or an earlier write by
                # someone else sits between and the run is not contiguous.
                if any(w != reason for _x, w in revs[i:]):
                    skipped_inner = True
                    break
                revertable.append((page, revs[i][0], f"{len(revs) - i} write(s) by {reason}"))
                break
        if skipped_inner:
            skipped.append((page, None, "the pass's writes are not the most recent run"))
    return revertable, skipped


def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    if len(args) != 1:
        sys.exit(__doc__.strip().split("\n\n")[0] + "\n\n"
                 "Usage: python3 tools/undo_pass.py <reason> [--dry-run] [--diff]")
    reason = agent._REASON_RE.sub("-", args[0].strip().lower()).strip("-")
    dry, show_diff = "--dry-run" in sys.argv, "--diff" in sys.argv

    for name in _NO_HISTORY:
        if (agent.WIKI_DIR / name).exists():
            print(f"note: wiki/{name} keeps no history, so this cannot restore it "
                  f"(index.md is regenerated by rebuild_index; log.md is append-only).")

    revertable, skipped = plan(reason)
    if not revertable and not skipped:
        print(f"\nNothing in wiki/.history was written by '{reason}'.")
        return 0

    for page, rev, why in revertable:
        rel = page.relative_to(agent.WIKI_DIR)
        old = rev.read_text(encoding="utf-8", errors="replace")
        new = page.read_text(encoding="utf-8", errors="replace")
        d = list(difflib.unified_diff(new.splitlines(), old.splitlines(),
                                      f"a/{rel}", f"b/{rel}", lineterm=""))
        adds = sum(1 for l in d if l.startswith("+") and not l.startswith("+++"))
        dels = sum(1 for l in d if l.startswith("-") and not l.startswith("---"))
        print(f"  {'[dry-run] ' if dry else ''}{rel}: restoring +{adds} -{dels} ({why})")
        if show_diff:
            print("\n".join("      " + l for l in d))
        if not dry:
            # A fresh scope per page. _snapshot_version records one revision per page per
            # scope, and this process has written nothing yet — so without it the first
            # page would be recorded and the rest silently would not, leaving an undo that
            # cannot itself be undone. Caught by a test asserting the revision exists.
            begin_write_scope()
            with write_reason(f"undo-{reason}"):
                _atomic_write(page, old)

    if skipped:
        print(f"\nLeft alone ({len(skipped)}):")
        for page, _rev, why in skipped:
            print(f"  {page.relative_to(agent.WIKI_DIR)}: {why}")

    verb = "Would restore" if dry else "Restored"
    print(f"\n{verb} {len(revertable)} page(s); left {len(skipped)} alone.")
    if not dry and revertable:
        print(f"The revert is itself recorded as 'undo-{reason}', so it can be undone too.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
